version: '3.8'

services:
  angular-app:
    build: .
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.ngland.tls=true'
      - 'traefik.http.routers.ngland.tls.certresolver=myresolver'
      - 'traefik.http.routers.ngland.entrypoints=websecure'
      - 'traefik.http.routers.ngland.rule=Host(`ng-land.wsofter.com`)'
      - 'traefik.http.services.ngland.loadbalancer.server.port=4200'
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true